#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_doc_comments)]
#![allow(unused_mut)]

mod auth;
mod cloud;
mod embedded_rules;
mod engine;
mod mcp;
mod onboarding;
mod parser;
mod remediation;
mod reporting;
mod scanner;
mod tui;

// New modules added by CLI overhaul
mod audit;
mod baseline;
mod benchmark;
mod cache;
mod cli;
mod confidence;
mod config;
mod diff;
mod hook;
mod key_manager;
mod lsp;
mod output;
mod publish;
mod rule_harness;
mod snippet;
mod suppression_learner;
mod telemetry;
mod verification;

use anyhow::Result;
use clap::Parser;
use std::path::PathBuf;

use cli::exit_code::ExitCode;
use cli::{Command, CompletionsArgs, LoginArgs, SicarioCli};

fn main() {
    // CRITICAL: When running as an MCP stdio server, stdout is reserved for
    // JSON-RPC 2.0 responses. The tracing subscriber MUST write to stderr.
    // The default fmt() writer is stdout — we must explicitly redirect to stderr.
    let args_peek: Vec<String> = std::env::args().collect();
    let is_mcp = args_peek.iter().any(|a| a == "mcp");

    if is_mcp {
        // MCP mode: redirect ALL tracing output to stderr, suppress below WARN
        tracing_subscriber::fmt()
            .with_writer(std::io::stderr)
            .with_max_level(tracing::Level::WARN)
            .with_ansi(false)
            .init();
    } else {
        // Normal CLI mode: default writer (stdout) is fine
        tracing_subscriber::fmt()
            .with_max_level(tracing::Level::WARN)
            .init();
    }

    let cli = SicarioCli::parse();

    let result = run(cli);

    match result {
        Ok(code) => std::process::exit(code as i32),
        Err(e) => {
            eprintln!("sicario: {e}");
            std::process::exit(ExitCode::InternalError as i32);
        }
    }
}

fn run(cli: SicarioCli) -> Result<ExitCode> {
    match cli.command {
        None => {
            // Default: scan current directory (headless CLI-first approach)
            let args = cli::scan::ScanArgs::default();
            cmd_scan(args)
        }
        Some(cmd) => dispatch(cmd),
    }
}

fn dispatch(cmd: Command) -> Result<ExitCode> {
    match cmd {
        Command::Scan(args) => cmd_scan(*args),
        Command::Init => {
            let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
            let config_path = cwd.join(".sicario").join("config.yaml");
            if config_path.exists() {
                eprintln!("sicario: .sicario/config.yaml already exists. Skipping init.");
                return Ok(ExitCode::Clean);
            }
            // Detect languages and write a default config
            use onboarding::detector::TechDetector;
            let detector = TechDetector;
            let result = TechDetector::detect(&cwd).unwrap_or_default();
            let languages: Vec<&str> = result.languages.iter().map(|l| l.as_str()).collect();
            std::fs::create_dir_all(cwd.join(".sicario"))?;
            let config_content = format!(
                "# Sicario configuration\n# Generated by `sicario init`\nlanguages:\n{}\n",
                languages
                    .iter()
                    .map(|l| format!("  - {}", l))
                    .collect::<Vec<_>>()
                    .join("\n")
            );
            std::fs::write(&config_path, config_content)?;
            eprintln!(
                "sicario: initialized .sicario/config.yaml (detected: {})",
                if languages.is_empty() {
                    "none".to_string()
                } else {
                    languages.join(", ")
                }
            );
            Ok(ExitCode::Clean)
        }
        Command::Report(args) => {
            cmd_report_handler(&args.dir, args.output.as_deref())?;
            Ok(ExitCode::Clean)
        }
        Command::Fix(args) => cmd_fix(args),
        Command::Baseline(args) => cmd_baseline(args),
        Command::Config(args) => cmd_config(args),
        Command::Suppressions(args) => cmd_suppressions(args),
        Command::Completions(args) => {
            cmd_completions(args);
            Ok(ExitCode::Clean)
        }
        Command::Login(args) => cmd_cloud_login(args),
        Command::Logout => cmd_cloud_logout(),
        Command::Publish(args) => cmd_cloud_publish(args.org),
        Command::Whoami => cmd_cloud_whoami(),
        Command::Tui(args) => {
            let scan_dir = PathBuf::from(&args.dir);
            run_interactive_tui(scan_dir)?;
            Ok(ExitCode::Clean)
        }
        Command::Hook(args) => cmd_hook(args),
        Command::Lsp(_args) => {
            let project_root = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
            let rule_paths = crate::lsp::discover_rule_paths(&project_root);
            let server = crate::lsp::SicarioLspServer::new(project_root, rule_paths);
            server.run()?;
            Ok(ExitCode::Clean)
        }
        Command::Benchmark(args) => cmd_benchmark(args),
        Command::Rules(args) => cmd_rules(args),
        Command::Cache(args) => cmd_cache(args),
        Command::Link(args) => {
            crate::cli::link::cmd_link(args)?;
            Ok(ExitCode::Clean)
        }
        Command::Mcp => {
            crate::mcp::kiro_tools::StdioMcpRunner::run()?;
            Ok(ExitCode::Clean)
        }
    }
}

// ─── Rules-dir loading helper ─────────────────────────────────────────────────

/// Load YAML rule files from a user-specified `--rules-dir` path into `eng`.
///
/// Returns `(rules_loaded, warning_message)` where `warning_message` is `Some`
/// when the path does not exist or contains no valid YAML rule files.  The
/// caller is responsible for printing the warning (so that tests can inspect
/// it without capturing stderr).
///
/// The function never exits the process — it always continues with whatever
/// rules are already loaded in `eng`.
pub fn load_rules_from_dir(
    rules_dir_path: &str,
    eng: &mut engine::sast_engine::SastEngine,
    quiet: bool,
) -> (usize, Option<String>) {
    let rules_dir = PathBuf::from(rules_dir_path);

    if !rules_dir.exists() {
        let msg = format!(
            "[sicario] warning: --rules-dir path does not exist: {}. Using built-in rules only.",
            rules_dir_path
        );
        if !quiet {
            eprintln!("{}", msg);
        }
        return (0, Some(msg));
    }

    match std::fs::read_dir(&rules_dir) {
        Ok(entries) => {
            let mut yaml_files: Vec<PathBuf> = entries
                .filter_map(|e| e.ok())
                .map(|e| e.path())
                .filter(|p| {
                    p.extension()
                        .and_then(|e| e.to_str())
                        .map(|e| e == "yaml" || e == "yml")
                        .unwrap_or(false)
                })
                .collect();
            yaml_files.sort();

            let mut user_rules_loaded = 0usize;
            for f in &yaml_files {
                if eng.load_rules(f).is_ok() {
                    user_rules_loaded += 1;
                }
            }

            if user_rules_loaded == 0 {
                let msg = format!(
                    "[sicario] warning: --rules-dir path contains no valid YAML rule files: {}. Using built-in rules only.",
                    rules_dir_path
                );
                if !quiet {
                    eprintln!("{}", msg);
                }
                return (0, Some(msg));
            }

            (user_rules_loaded, None)
        }
        Err(e) => {
            let msg = format!(
                "[sicario] warning: could not read --rules-dir '{}': {}. Using built-in rules only.",
                rules_dir_path, e
            );
            if !quiet {
                eprintln!("{}", msg);
            }
            (0, Some(msg))
        }
    }
}

// ─── Embedded rule loader ─────────────────────────────────────────────────────

/// Load all rules embedded in the binary at compile time into `eng`.
///
/// This is the primary rule-loading path for installed binaries — the entire
/// `rules/` directory is compiled in via `rust-embed` so the full rule set is
/// always available regardless of the filesystem layout on the user's machine.
///
/// Returns the number of rule files successfully parsed.
fn load_embedded_rules_into(eng: &mut engine::sast_engine::SastEngine) -> usize {
    use crate::embedded_rules::iter_embedded_rules;

    let mut files_loaded = 0usize;
    for (path, yaml_content) in iter_embedded_rules() {
        match serde_yaml::from_str::<Vec<engine::security_rule::SecurityRule>>(&yaml_content) {
            Ok(rules) => {
                for rule in rules {
                    let _ = eng.load_rule_direct(rule);
                }
                files_loaded += 1;
            }
            Err(e) => {
                tracing::warn!("Skipping embedded rule file '{}': {}", path, e);
            }
        }
    }
    files_loaded
}

// ─── Scan command ─────────────────────────────────────────────────────────────

fn cmd_scan(args: cli::scan::ScanArgs) -> Result<ExitCode> {
    use cli::exit_code::FindingSummary;
    use cli::scan::OutputFormat;
    use engine::sast_engine::SastEngine;
    use engine::vulnerability::Severity;
    use output::branded::{print_scan_summary, ScanSummary};
    use output::formatter::{render_finding_text, render_findings_table, FormatterConfig};
    use output::sarif::emit_sarif;

    let scan_start = std::time::Instant::now();
    let dir = PathBuf::from(args.resolved_dir());

    let formatter_config = FormatterConfig::from_flags(
        args.no_color,
        args.force_color,
        args.max_lines_per_finding,
        args.max_chars_per_line,
    );

    let explicit: Vec<PathBuf> = args.rules.iter().map(PathBuf::from).collect();

    let mut eng = SastEngine::new(&dir)?;
    let mut rules_loaded = 0usize;

    if !explicit.is_empty() {
        // User passed explicit --rules flags — load only those files.
        for f in &explicit {
            if eng.load_rules(f).is_ok() {
                rules_loaded += 1;
            }
        }
    } else {
        // Normal path: always load the full embedded rule set first.
        // This is the production path — 500+ rules compiled into the binary.
        rules_loaded = load_embedded_rules_into(&mut eng);
        tracing::debug!(
            "Loaded {} embedded rule files ({} rules)",
            rules_loaded,
            eng.get_rules().len()
        );

        // If embedded rules produced nothing (dev build without rust-embed),
        // fall back to rules/ on disk so development still works.
        if eng.get_rules().is_empty() {
            let disk_files = discover_bundled_rules();
            for f in &disk_files {
                if eng.load_rules(f).is_ok() {
                    rules_loaded += 1;
                }
            }
        }
    }

    // Load user rules from --rules-dir (user rules take precedence on ID conflicts)
    if let Some(ref rules_dir_path) = args.rules_dir {
        let (loaded, _warning) = load_rules_from_dir(rules_dir_path, &mut eng, args.quiet);
        rules_loaded += loaded;
    }

    // If no rule files were found on disk, fall back to the hardcoded default
    // rules so the AST engine always has at least one active rule.
    if eng.get_rules().is_empty() {
        eng.load_default_rules();
    }
    // Count files to scan for the summary — also capture ignored count
    let mut files_to_scan = Vec::new();
    let files_ignored = eng.collect_files_with_ignored_count(&dir, &mut files_to_scan)?;
    let files_scanned = files_to_scan.len();
    let total_rules = eng.get_rules().len();
    // rules_loaded reflects YAML files loaded; if we fell back to defaults,
    // report the actual number of active rules instead.
    if rules_loaded == 0 && total_rules > 0 {
        rules_loaded = total_rules;
    }

    let mut vulns = eng.scan_directory(&dir)?;
    let scan_duration = scan_start.elapsed();

    // ── Snippet extraction (zero-exfiltration guarantee) ──────────────────
    // Re-extract snippets for each finding using the configured context window,
    // enforcing the 100-char-per-line truncation before any telemetry submission.
    {
        use snippet::extractor::{SnippetConfig, SnippetExtractor};

        let context_lines = match args.resolve_snippet_context() {
            Ok(n) => n,
            Err(msg) => {
                eprintln!("sicario: {msg}");
                return Ok(ExitCode::InternalError);
            }
        };
        let snippet_config = SnippetConfig::new(context_lines, 100);

        for vuln in &mut vulns {
            // Only re-extract for real file paths (skip synthetic SCA entries like <ecosystem/pkg>)
            let path_str = vuln.file_path.to_string_lossy();
            if path_str.starts_with('<') {
                continue;
            }
            let abs_path = if vuln.file_path.is_absolute() {
                vuln.file_path.clone()
            } else {
                dir.join(&vuln.file_path)
            };
            if let Ok(content) = std::fs::read_to_string(&abs_path) {
                vuln.snippet = SnippetExtractor::extract(&content, vuln.line, &snippet_config);
            }
        }
    }

    // Cloud exposure analysis: auto-detect K8s manifests and adjust priorities
    if !args.no_cloud {
        use cloud::exposure::CloudExposureAnalyzer;
        use cloud::priority::assign_cloud_priority;

        let mut analyzer = CloudExposureAnalyzer::new();
        let mut k8s_found = false;

        // Search for K8s manifest directories
        let k8s_dirs = ["k8s", "kubernetes", "deploy", "manifests", ".k8s"];
        for k8s_dir in &k8s_dirs {
            let candidate = dir.join(k8s_dir);
            if candidate.is_dir() && analyzer.load_kubernetes_configs(&candidate).is_ok() {
                k8s_found = true;
            }
        }

        // Also scan the project root for YAML files with K8s manifests
        if !k8s_found {
            // Check if any YAML files in the root look like K8s manifests
            if analyzer.load_kubernetes_configs(&dir).is_ok() {
                k8s_found = true;
            }
        }

        // Check for CSPM data directories
        let cspm_dirs = ["cspm", ".cspm", "cloud-security"];
        for cspm_dir in &cspm_dirs {
            let candidate = dir.join(cspm_dir);
            if candidate.is_dir() {
                let _ = analyzer.load_cspm_findings(&candidate);
            }
        }

        if k8s_found {
            assign_cloud_priority(&mut vulns, &analyzer);
        }
    }

    // ── SCA: dependency vulnerability scanning ────────────────────────────
    // Architecture: AST scanning never waits for network. The OSV cache refresh
    // is fired off in a background thread (fire-and-forget). The local SQLite
    // cache query runs immediately after — if the cache is empty, SCA findings
    // will simply be absent this run and populated on the next scan.
    {
        use engine::sca::manifest_parser::ManifestParser;
        use engine::sca::VulnerabilityDatabaseManager;

        let cache_dir = dir.join(".sicario").join("cache");
        match VulnerabilityDatabaseManager::new(&cache_dir) {
            Ok(vuln_db) => {
                // Parse lockfiles/manifests to find all dependencies
                let deps = ManifestParser::parse_directory(&dir).unwrap_or_default();

                if !deps.is_empty() {
                    // Build tuples for the OSV query
                    let dep_tuples: Vec<(String, String, String)> = deps
                        .iter()
                        .filter(|d| !d.version.is_empty())
                        .map(|d| {
                            (
                                d.ecosystem.clone(),
                                d.package_name.clone(),
                                d.version.clone(),
                            )
                        })
                        .collect();

                    // Kick off OSV cache refresh in a background thread so it
                    // never blocks the AST pipeline. Zero-exfiltration guarantee:
                    // if the network is unavailable the scan still completes
                    // instantly using whatever is already in the local cache.
                    if let Ok(true) = vuln_db.is_stale() {
                        let bg_cache_dir = cache_dir.clone();
                        let bg_dep_tuples = dep_tuples.clone();
                        std::thread::spawn(move || {
                            match VulnerabilityDatabaseManager::new(&bg_cache_dir) {
                                Ok(bg_db) => match bg_db.refresh_if_stale(&bg_dep_tuples) {
                                    Ok(count) => {
                                        tracing::debug!(
                                            "SCA background cache refresh: {} records updated",
                                            count
                                        );
                                    }
                                    Err(e) => {
                                        tracing::warn!(
                                                "SCA background cache refresh failed (scan unaffected): {}",
                                                e
                                            );
                                    }
                                },
                                Err(e) => {
                                    tracing::warn!("SCA background db init failed: {}", e);
                                }
                            }
                        });
                    }

                    // Query local cache for each dependency (pure SQLite, no network)
                    for dep in &deps {
                        if dep.version.is_empty() {
                            continue;
                        }
                        match vuln_db.query_package(&dep.ecosystem, &dep.package_name, &dep.version)
                        {
                            Ok(known_vulns) => {
                                for kv in known_vulns {
                                    let rule_id = format!(
                                        "sca/{}",
                                        kv.cve_id
                                            .as_deref()
                                            .or(kv.ghsa_id.as_deref())
                                            .unwrap_or("unknown")
                                    );
                                    let snippet = format!(
                                        "{}@{} — {}",
                                        dep.package_name, dep.version, kv.summary
                                    );
                                    let mut sca_vuln = engine::vulnerability::Vulnerability::new(
                                        rule_id,
                                        PathBuf::from(format!(
                                            "<{}/{}>",
                                            dep.ecosystem, dep.package_name
                                        )),
                                        0,
                                        0,
                                        snippet,
                                        kv.severity,
                                    );
                                    sca_vuln.owasp_category =
                                        Some(engine::vulnerability::OwaspCategory::A06_VulnerableComponents);
                                    sca_vuln.cwe_id = kv.cve_id.clone();
                                    vulns.push(sca_vuln);
                                }
                            }
                            Err(e) => {
                                tracing::debug!(
                                    "SCA query failed for {}/{}: {}",
                                    dep.ecosystem,
                                    dep.package_name,
                                    e
                                );
                            }
                        }
                    }
                }
            }
            Err(e) => {
                tracing::warn!("Failed to initialize SCA database: {}", e);
                if !args.quiet {
                    eprintln!("warning: SCA scanning unavailable: {e}");
                }
            }
        }
    }

    // ── Severity filter ───────────────────────────────────────────────────
    // Apply --min-severity / -s before any output or summary tallying.
    // The Severity enum derives PartialOrd/Ord with Info < Low < Medium < High < Critical,
    // so a simple >= comparison is all that's needed.
    let min_severity: Severity = args.min_severity.into();
    vulns.retain(|v| v.severity >= min_severity);

    // Emit primary output in the requested format
    let mut stdout = std::io::stdout();
    match args.format {
        OutputFormat::Json => {
            println!("{}", serde_json::to_string_pretty(&vulns)?);
        }
        OutputFormat::Text => {
            if args.quiet {
                // Quiet mode: just the summary line
            } else {
                output::diagnostics::render_diagnostics(
                    &vulns,
                    formatter_config.color_enabled,
                    &mut stdout,
                )?;
            }
            let summary = ScanSummary::from_vulns_full(
                &vulns,
                scan_duration,
                files_scanned,
                files_ignored,
                total_rules,
                min_severity,
            );
            print_scan_summary(
                &summary,
                formatter_config.unicode_enabled,
                formatter_config.color_enabled,
                &mut stdout,
            )?;
        }
        OutputFormat::Sarif => {
            let tool_version = env!("CARGO_PKG_VERSION");
            let sarif_doc = emit_sarif(&vulns, tool_version);
            println!("{}", serde_json::to_string_pretty(&sarif_doc)?);
        }
    }

    // Write simultaneous multi-format output to files
    if let Some(ref json_path) = args.json_output {
        let json_str = serde_json::to_string_pretty(&vulns)?;
        std::fs::write(json_path, json_str)?;
        if !args.quiet {
            eprintln!("JSON output written to {json_path}");
        }
    }

    if let Some(ref sarif_path) = args.sarif_output {
        let tool_version = env!("CARGO_PKG_VERSION");
        let sarif_doc = emit_sarif(&vulns, tool_version);
        let sarif_str = serde_json::to_string_pretty(&sarif_doc)?;
        std::fs::write(sarif_path, sarif_str)?;
        if !args.quiet {
            eprintln!("SARIF output written to {sarif_path}");
        }
    }

    if let Some(ref text_path) = args.text_output {
        let mut buf = Vec::new();
        for v in &vulns {
            render_finding_text(v, &formatter_config, &mut buf)?;
        }
        let summary = ScanSummary::from_vulns_full(
            &vulns,
            scan_duration,
            files_scanned,
            files_ignored,
            total_rules,
            min_severity,
        );
        print_scan_summary(
            &summary, false, // no unicode in file output
            false, // no color in file output
            &mut buf,
        )?;
        std::fs::write(text_path, buf)?;
        if !args.quiet {
            eprintln!("Text output written to {text_path}");
        }
    }

    // Resolve exit-code gating values before args fields are partially moved
    let severity_threshold: Severity = match args.resolve_fail_on() {
        Ok(s) => s,
        Err(msg) => {
            eprintln!("sicario: {msg}");
            return Ok(ExitCode::InternalError);
        }
    };
    let confidence_threshold = args.confidence_threshold;
    let in_github_actions = std::env::var("GITHUB_ACTIONS").is_ok();

    // Auto-publish to Sicario Cloud via telemetry endpoint if --publish flag is set
    if args.publish {
        submit_telemetry(
            &vulns,
            scan_duration,
            rules_loaded,
            files_scanned,
            args.org.clone(),
            args.publish_all,
        );
    }

    // Compute exit code
    let summaries: Vec<FindingSummary> = vulns
        .iter()
        .map(|v| FindingSummary {
            severity: v.severity,
            confidence_score: 1.0, // confidence scoring not yet wired
            suppressed: false,     // suppression not yet wired
        })
        .collect();

    let exit_code = ExitCode::from_findings(&summaries, severity_threshold, confidence_threshold);

    // GitHub Actions annotation — only emit for non-JSON formats so the
    // annotation lines don't corrupt machine-readable output.
    if in_github_actions && !matches!(args.format, OutputFormat::Json | OutputFormat::Sarif) {
        let above_threshold = summaries
            .iter()
            .filter(|f| !f.suppressed && f.severity >= severity_threshold)
            .count();
        if above_threshold > 0 {
            println!(
                "::warning title=Sicario Security Scan::Found {above_threshold} finding(s) at or above {} severity. Build will fail.",
                severity_threshold
            );
        } else {
            println!("::notice title=Sicario Security Scan::No findings at or above {} severity. Build passed.", severity_threshold);
        }
    }

    // ── Watch mode ────────────────────────────────────────────────────────
    if args.watch {
        run_watch_mode(&dir, &args, exit_code)?;
        return Ok(ExitCode::Clean);
    }

    Ok(exit_code)
}

// ── Watch mode ────────────────────────────────────────────────────────────────

/// A finding identity key used to diff watch-mode scans.
///
/// Stores the rule_id, line number, and severity so we can emit the correct
/// `[resolved] <rule_id> at <file>:<line>` format (Req 18.5) and accurately
/// update the live summary counters when findings are resolved.
#[derive(Clone, PartialEq, Eq)]
struct FindingKey {
    rule_id: String,
    line: usize,
    severity: engine::vulnerability::Severity,
}

impl FindingKey {
    fn new(
        rule_id: impl Into<String>,
        line: usize,
        severity: engine::vulnerability::Severity,
    ) -> Self {
        Self {
            rule_id: rule_id.into(),
            line,
            severity,
        }
    }
}

/// Recompute the aggregate severity counts from all currently tracked findings.
///
/// This is called after every scan event to produce an accurate live summary
/// line rather than relying on incremental counter arithmetic (which can drift
/// when the same finding appears/disappears across multiple rapid saves).
fn compute_watch_summary(
    prev_findings: &std::collections::HashMap<String, Vec<FindingKey>>,
) -> (u32, u32, u32, u32) {
    use engine::vulnerability::Severity;
    let mut critical = 0u32;
    let mut high = 0u32;
    let mut medium = 0u32;
    let mut low = 0u32;
    for keys in prev_findings.values() {
        for fk in keys {
            match fk.severity {
                Severity::Critical => critical += 1,
                Severity::High => high += 1,
                Severity::Medium => medium += 1,
                _ => low += 1, // Low + Info both count as "Low" in the summary
            }
        }
    }
    (critical, high, medium, low)
}

/// Print (or overwrite) the live watch summary line.
///
/// On a TTY, uses `\r` to overwrite the current line in-place so the summary
/// stays at the bottom of the terminal without scrolling.  On a non-TTY (e.g.
/// piped output, CI), falls back to a plain newline so the log is readable.
fn print_watch_summary(critical: u32, high: u32, medium: u32, low: u32, is_tty: bool) {
    let line = format!(
        "[watch] Critical: {}  High: {}  Medium: {}  Low: {}",
        critical, high, medium, low
    );
    if is_tty {
        // Pad to 80 chars to overwrite any longer previous line, then \r to
        // return the cursor to the start of the line without advancing.
        eprint!("\r{:<80}\r{}", "", line);
    } else {
        eprintln!("{}", line);
    }
}

/// Run the scanner in continuous watch mode.
///
/// Uses `notify` to watch the target directory for file changes, debounces
/// events by 100ms, and re-scans only the affected file on each change.
/// Respects `.gitignore` and `.sicarioignore` patterns via the `ExclusionManager`.
/// Handles Ctrl+C with a clean exit code 0.
///
/// Requirements: 18.1, 18.2, 18.4, 18.5, 18.6
fn run_watch_mode(
    dir: &std::path::Path,
    args: &cli::scan::ScanArgs,
    _initial_exit_code: ExitCode,
) -> Result<()> {
    use engine::sast_engine::SastEngine;
    use engine::vulnerability::Vulnerability;
    use notify::{RecursiveMode, Watcher};
    use notify_debouncer_mini::new_debouncer;
    use output::formatter::FormatterConfig;
    use parser::ExclusionManager;
    use std::collections::HashMap;
    use std::io::IsTerminal;
    use std::sync::mpsc;
    use std::time::Duration;

    // Detect color support for diagnostic output
    let color_enabled = std::io::stderr().is_terminal();
    // Detect whether stderr is a TTY for in-place summary line updates
    let is_tty = std::io::stderr().is_terminal();

    eprintln!(
        "[watch] Watching {} for changes. Press Ctrl+C to exit.",
        dir.display()
    );

    // Build the exclusion manager once for the watched directory.
    // This loads .gitignore and .sicarioignore patterns from `dir` so that
    // file change events for excluded paths are silently skipped (Req 18.6).
    let exclusion_manager =
        ExclusionManager::new(dir).unwrap_or_else(|_| ExclusionManager::empty());

    // Set up Ctrl+C (SIGINT) handler using a shared atomic flag.
    // When the user presses Ctrl+C, the flag is set to false and the main
    // watch loop exits cleanly, printing "[watch] Exiting..." and returning
    // exit code 0 (Req 18.3).
    let running = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(true));
    {
        let r = running.clone();
        ctrlc::set_handler(move || {
            r.store(false, std::sync::atomic::Ordering::SeqCst);
        })
        .unwrap_or_else(|e| {
            eprintln!("[watch] warning: could not set Ctrl+C handler: {e}");
        });
    }

    let (tx, rx) = mpsc::channel();

    let mut debouncer = new_debouncer(Duration::from_millis(100), tx)
        .map_err(|e| anyhow::anyhow!("Failed to create file watcher: {e}"))?;

    debouncer
        .watcher()
        .watch(dir, RecursiveMode::Recursive)
        .map_err(|e| anyhow::anyhow!("Failed to watch directory: {e}"))?;

    // Track previous findings per file for diff.
    // Key: canonical file path string → Vec of FindingKey (rule_id + line + severity).
    let mut prev_findings: HashMap<String, Vec<FindingKey>> = HashMap::new();

    while running.load(std::sync::atomic::Ordering::SeqCst) {
        match rx.recv_timeout(Duration::from_millis(200)) {
            Ok(Ok(events)) => {
                for event in events {
                    let path = &event.path;

                    // Skip non-source files
                    let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
                    let is_source = matches!(
                        ext,
                        "js" | "ts" | "jsx" | "tsx" | "py" | "rs" | "go" | "java"
                    );
                    if !is_source {
                        continue;
                    }

                    // Respect .gitignore and .sicarioignore exclusion patterns (Req 18.6).
                    // If the changed file matches any exclusion pattern, skip it silently.
                    if exclusion_manager.is_excluded(path) {
                        continue;
                    }

                    let file_key = path.to_string_lossy().to_string();

                    if !path.exists() {
                        // File deleted — mark all its findings as resolved (Req 18.5)
                        if let Some(old) = prev_findings.remove(&file_key) {
                            for fk in &old {
                                eprintln!("[resolved] {} at {}:{}", fk.rule_id, file_key, fk.line);
                                // Emit zero-exfiltration receipt for each resolved finding
                                if !args.no_receipt {
                                    let receipt = remediation::PatchReceipt::deterministic(
                                        &fk.rule_id,
                                        &file_key,
                                        fk.line as u32,
                                        0,
                                        &fk.rule_id,
                                    );
                                    receipt.print();
                                }
                            }
                        }
                        // Recompute and print the live summary after deletion
                        let (c, h, m, l) = compute_watch_summary(&prev_findings);
                        print_watch_summary(c, h, m, l, is_tty);
                        continue;
                    }

                    // Re-scan the affected file
                    let mut eng = match SastEngine::new(dir) {
                        Ok(e) => e,
                        Err(_) => continue,
                    };

                    // Load rules
                    let rule_files = discover_bundled_rules();
                    for f in &rule_files {
                        let _ = eng.load_rules(f);
                    }
                    if eng.get_rules().is_empty() {
                        eng.load_default_rules();
                    }

                    let new_vulns: Vec<Vulnerability> = eng.scan_file(path).unwrap_or_default();

                    // Build the new finding key set (includes severity for accurate summary)
                    let new_keys: Vec<FindingKey> = new_vulns
                        .iter()
                        .map(|v| FindingKey::new(&v.rule_id, v.line, v.severity))
                        .collect();

                    let old_keys = prev_findings.get(&file_key).cloned().unwrap_or_default();

                    // ── Print NEW findings in standard diagnostic format (Req 18.4) ──
                    // Collect only the truly new findings (absent from the previous scan).
                    let new_findings: Vec<&Vulnerability> = new_vulns
                        .iter()
                        .filter(|v| {
                            !old_keys
                                .iter()
                                .any(|fk| fk.rule_id == v.rule_id && fk.line == v.line)
                        })
                        .collect();

                    if !new_findings.is_empty() {
                        let mut stderr = std::io::stderr();
                        // Render each new finding using the same diagnostic format as
                        // `sicario scan` (miette-style with source context box).
                        for v in &new_findings {
                            let single = std::slice::from_ref(*v);
                            let _ = output::diagnostics::render_diagnostics(
                                single,
                                color_enabled,
                                &mut stderr,
                            );
                        }
                    }

                    // ── Print RESOLVED findings (Req 18.5) ──
                    // Format: `[resolved] <rule_id> at <file>:<line>`
                    for fk in &old_keys {
                        if !new_keys
                            .iter()
                            .any(|nk| nk.rule_id == fk.rule_id && nk.line == fk.line)
                        {
                            eprintln!("[resolved] {} at {}:{}", fk.rule_id, file_key, fk.line);
                            // Emit zero-exfiltration receipt for each resolved finding
                            if !args.no_receipt {
                                let receipt = remediation::PatchReceipt::deterministic(
                                    &fk.rule_id,
                                    &file_key,
                                    fk.line as u32,
                                    0,
                                    &fk.rule_id,
                                );
                                receipt.print();
                            }
                        }
                    }

                    // Update stored findings for this file
                    prev_findings.insert(file_key, new_keys);

                    // Recompute and print the live summary line (Req 18.6)
                    // Counts are derived from the full prev_findings map so they
                    // are always accurate regardless of add/remove ordering.
                    let (c, h, m, l) = compute_watch_summary(&prev_findings);
                    print_watch_summary(c, h, m, l, is_tty);
                }
            }
            Ok(Err(errors)) => {
                eprintln!("[watch] watcher error: {errors}");
            }
            Err(mpsc::RecvTimeoutError::Timeout) => {
                // No events — check running flag
            }
            Err(mpsc::RecvTimeoutError::Disconnected) => {
                break;
            }
        }
    }

    eprintln!("\n[watch] Exiting...");
    Ok(())
}

/// Submit scan results to the zero-exfiltration telemetry endpoint (best-effort, never fails the scan).
///
/// Resolves auth via the 5-level priority chain, builds a TelemetryPayload from
/// the scan results, and POSTs to `POST /api/v1/telemetry/scan`.
///
/// By default only Medium+ findings are submitted to keep the dashboard signal-to-noise
/// ratio high. Pass `publish_all = true` (via `--publish --publish-all`) to submit
/// the full finding set including Low and Info.
///
/// Requirements: 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 15.1, 15.2
fn submit_telemetry(
    vulns: &[engine::vulnerability::Vulnerability],
    scan_duration: std::time::Duration,
    rules_loaded: usize,
    files_scanned: usize,
    org_id: Option<String>,
    publish_all: bool,
) {
    use publish::{
        collect_git_metadata, resolve_cloud_url, TelemetryClient, TelemetryFinding,
        TelemetryPayload,
    };

    // ── Unauthenticated guard ─────────────────────────────────────────────
    // Check whether any credential is available before attempting to publish.
    // We mirror the 5-level priority chain from AuthModule::resolve_auth_token()
    // without touching the network or the keychain for the check itself.
    //
    // If no credential is found at all, print a friendly sign-up prompt and
    // return with exit code 0 (not a scan failure).
    {
        use auth::token_store::TokenStore;

        let has_sicario_api_key = std::env::var("SICARIO_API_KEY")
            .map(|v| !v.is_empty())
            .unwrap_or(false);
        let has_project_api_key = std::env::var("SICARIO_PROJECT_API_KEY")
            .map(|v| !v.is_empty())
            .unwrap_or(false);
        let has_cloud_token = TokenStore::new()
            .ok()
            .and_then(|ts| ts.get_cloud_token().ok())
            .map(|t| !t.is_empty())
            .unwrap_or(false);
        let has_keychain_project_key = TokenStore::new()
            .ok()
            .and_then(|ts| ts.get_project_api_key_from_keychain().ok())
            .map(|k| !k.is_empty())
            .unwrap_or(false);
        let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
        let has_config_api_key = crate::key_manager::config_file::load_config_file(&cwd)
            .and_then(|c| c.api_key)
            .map(|k| !k.is_empty())
            .unwrap_or(false);

        if !has_sicario_api_key
            && !has_cloud_token
            && !has_project_api_key
            && !has_keychain_project_key
            && !has_config_api_key
        {
            eprintln!("Publishing requires a free account. Sign up at https://usesicario.xyz/auth");
            return;
        }
    }

    // ── Telemetry severity gate ───────────────────────────────────────────
    // Default: only publish Medium and above to prevent Low/Info noise from
    // flooding the dashboard (e.g. unwrap() in test code).
    // Override with --publish --publish-all to send everything.
    let telemetry_min_severity = if publish_all {
        engine::vulnerability::Severity::Info
    } else {
        engine::vulnerability::Severity::Medium
    };

    let client_id =
        std::env::var("SICARIO_CLOUD_CLIENT_ID").unwrap_or_else(|_| "sicario-cli".to_string());
    let auth_url = std::env::var("SICARIO_CLOUD_AUTH_URL")
        .unwrap_or_else(|_| "https://flexible-terrier-680.convex.site".to_string());

    let auth_module = match auth::auth_module::AuthModule::new(client_id, auth_url) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("warning: --publish skipped (could not initialize auth module: {e})");
            return;
        }
    };

    let auth_token = match auth_module.resolve_auth_token() {
        Ok(t) => t,
        Err(e) => {
            eprintln!("warning: --publish skipped ({e})");
            return;
        }
    };

    // Read project ID from priority chain:
    // 1. SICARIO_PROJECT_ID env var
    // 2. .sicario/config.yaml (extra fields)
    // 3. ~/.sicario/config.toml (extra fields via global_config)
    let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
    let project_id = std::env::var("SICARIO_PROJECT_ID")
        .ok()
        .filter(|s| !s.is_empty())
        .or_else(|| {
            crate::key_manager::config_file::load_config_file(&cwd).and_then(|c| {
                c.extra
                    .get("project_id")
                    .and_then(|v| v.as_str().map(|s| s.to_string()))
            })
        })
        .or_else(|| {
            // Check global config (~/.sicario/config.toml)
            crate::config::global_config::load_global_config().and_then(|c| {
                c.extra
                    .get("project_id")
                    .and_then(|v| v.as_str().map(|s| s.to_string()))
            })
        })
        .unwrap_or_default();

    if project_id.is_empty() {
        eprintln!(
            "warning: --publish skipped (no project_id configured). \
             Run `sicario link --project=<PROJECT_ID>` or set SICARIO_PROJECT_ID."
        );
        return;
    }

    let (repository_url, branch, commit_sha) = collect_git_metadata();

    // Generate a unique scan ID
    let scan_id = format!(
        "scan-{}-{}",
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0),
        uuid::Uuid::new_v4()
            .to_string()
            .replace('-', "")
            .chars()
            .take(8)
            .collect::<String>()
            .to_uppercase()
    );

    // Map vulnerabilities to TelemetryFinding, skipping synthetic SCA entries
    // and applying the telemetry severity gate.
    let findings: Vec<TelemetryFinding> = vulns
        .iter()
        .filter(|v| v.severity >= telemetry_min_severity)
        .filter(|v| !v.file_path.to_string_lossy().starts_with('<'))
        .map(|v| {
            let severity_str = match v.severity {
                engine::vulnerability::Severity::Critical => "Critical",
                engine::vulnerability::Severity::High => "High",
                engine::vulnerability::Severity::Medium => "Medium",
                engine::vulnerability::Severity::Low => "Low",
                engine::vulnerability::Severity::Info => "Low", // map Info → Low for telemetry
            };
            // Truncate snippet to 100 chars as a final safety measure
            let snippet = if v.snippet.len() > 100 {
                v.snippet.chars().take(100).collect()
            } else {
                v.snippet.clone()
            };
            // Include execution trace if available
            let execution_trace = v.execution_trace.as_ref().map(|t| t.as_strings());
            TelemetryFinding {
                rule: v.rule_id.clone(),
                severity: severity_str.to_string(),
                file: v.file_path.to_string_lossy().to_string(),
                line: v.line,
                snippet,
                cwe_id: v.cwe_id.clone(),
                owasp_category: v.owasp_category.map(|c| format!("{:?}", c)),
                fingerprint: None,
                execution_trace,
            }
        })
        .collect();

    // Resolve optional PR number from environment (CI integration)
    let pr_number: Option<u32> = std::env::var("SICARIO_PR_NUMBER")
        .ok()
        .and_then(|s| s.parse().ok());

    // Count unique contributors in the last 90 days from local git history.
    // Only the integer count is included — no author names or emails are transmitted.
    let contributor_count = crate::telemetry::count_contributors(&cwd);

    let payload = TelemetryPayload {
        project_id,
        repository_url,
        commit_sha,
        scan_id: scan_id.clone(),
        branch: if branch.is_empty() {
            None
        } else {
            Some(branch)
        },
        pr_number,
        duration_ms: Some(scan_duration.as_millis() as u64),
        rules_loaded: Some(rules_loaded),
        files_scanned: Some(files_scanned),
        contributor_count,
        findings,
    };

    let cloud_url = resolve_cloud_url();
    let client = match TelemetryClient::new(cloud_url, auth_token) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("warning: --publish skipped (could not create telemetry client: {e})");
            return;
        }
    };

    match client.submit(&payload) {
        Ok(resp) => {
            eprintln!(
                "Scan published to Sicario Cloud (scan ID: {}).",
                resp.scan_id
            );
            if let Some(url) = resp.dashboard_url {
                eprintln!("  Dashboard: {url}");
            }
        }
        Err(e) => {
            eprintln!("warning: --publish failed: {e}");
        }
    }
}

/// Helper: publish scan results to Sicario Cloud via the legacy /api/v1/scans endpoint.
/// Used by `sicario cloud publish` for backward compatibility.
fn publish_scan_results(
    vulns: &[engine::vulnerability::Vulnerability],
    scan_duration: std::time::Duration,
    rules_loaded: usize,
    files_scanned: usize,
    language_breakdown: std::collections::HashMap<String, usize>,
    org_id: Option<String>,
) {
    use publish::{
        collect_git_metadata, resolve_cloud_url, PublishClient, ScanMetadata, ScanReport,
    };

    // Check for cloud auth token — silently skip if not authenticated
    let client_id =
        std::env::var("SICARIO_CLOUD_CLIENT_ID").unwrap_or_else(|_| "sicario-cli".to_string());
    let auth_url = std::env::var("SICARIO_CLOUD_AUTH_URL")
        .unwrap_or_else(|_| "https://flexible-terrier-680.convex.site".to_string());

    let auth_module = match auth::auth_module::AuthModule::new(client_id, auth_url) {
        Ok(m) => m,
        Err(_) => {
            eprintln!("warning: --publish skipped (could not initialize auth module)");
            return;
        }
    };

    let token = match auth_module.get_cloud_token() {
        Ok(t) => t,
        Err(_) => {
            eprintln!("warning: --publish skipped (not logged in). Run `sicario login` first.");
            return;
        }
    };

    let (repository, branch, commit_sha) = collect_git_metadata();

    let findings: Vec<engine::vulnerability::Finding> = vulns
        .iter()
        .map(|v| engine::vulnerability::Finding::from_vulnerability(v, &v.rule_id))
        .collect();

    let metadata = ScanMetadata {
        repository,
        branch,
        commit_sha,
        timestamp: chrono::Utc::now(),
        duration_ms: scan_duration.as_millis() as u64,
        rules_loaded,
        files_scanned,
        language_breakdown,
        tags: Vec::new(),
    };

    let report = ScanReport { findings, metadata };
    let cloud_url = resolve_cloud_url();

    let client = match PublishClient::new(cloud_url, token) {
        Ok(c) => c.with_org(org_id),
        Err(e) => {
            eprintln!("warning: --publish skipped ({e})");
            return;
        }
    };

    match client.publish(&report) {
        Ok(resp) => {
            eprintln!(
                "Scan published to Sicario Cloud (scan ID: {}).",
                resp.scan_id
            );
            if let Some(url) = resp.dashboard_url {
                eprintln!("  Dashboard: {url}");
            }
        }
        Err(e) => {
            eprintln!("warning: --publish failed: {e}");
        }
    }
}

/// Build a language breakdown HashMap from file extensions.
///
/// Maps file extension (lowercased, e.g. "rs", "js", "py") to the count of files
/// with that extension. Files without an extension are counted under "other".
fn build_language_breakdown(files: &[PathBuf]) -> std::collections::HashMap<String, usize> {
    let mut breakdown = std::collections::HashMap::new();
    for file in files {
        let ext = file
            .extension()
            .and_then(|e| e.to_str())
            .map(|e| e.to_lowercase())
            .unwrap_or_else(|| "other".to_string());
        *breakdown.entry(ext).or_insert(0) += 1;
    }
    breakdown
}

// ─── Suppressions command ──────────────────────────────────────────────────────

fn cmd_suppressions(args: cli::suppressions::SuppressionsCommand) -> Result<ExitCode> {
    use cli::suppressions::SuppressionsAction;
    use suppression_learner::SuppressionLearner;

    let project_root = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));

    match args.action {
        SuppressionsAction::List => {
            let learner = SuppressionLearner::load(&project_root)?;
            let patterns = learner.list();
            if patterns.is_empty() {
                println!("No learned suppression patterns.");
            } else {
                println!("{:<30} {:<8} Example Snippet", "Rule ID", "Count");
                println!("{}", "-".repeat(70));
                for p in patterns {
                    let snippet_preview: String = p.example_snippet.chars().take(40).collect();
                    println!("{:<30} {:<8} {}", p.rule_id, p.match_count, snippet_preview);
                }
            }
        }
        SuppressionsAction::Reset => {
            let mut learner = SuppressionLearner::load(&project_root)?;
            learner.reset();
            learner.save()?;
            println!("All learned suppression patterns have been cleared.");
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Shell completions ────────────────────────────────────────────────────────

fn cmd_completions(args: CompletionsArgs) {
    use clap::CommandFactory;
    use clap_complete::generate;

    let mut cmd = SicarioCli::command();
    generate(args.shell, &mut cmd, "sicario", &mut std::io::stdout());
}

// ─── Hook command ─────────────────────────────────────────────────────────────

fn cmd_hook(args: cli::hook::HookCommand) -> Result<ExitCode> {
    use cli::hook::HookAction;
    use hook::manager::{HookManagement, HookManager};

    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let mgr = HookManager::new(&cwd)?;

    match args.action {
        HookAction::Install => {
            mgr.install()?;
            eprintln!("sicario: pre-commit hook installed");
        }
        HookAction::Uninstall => {
            mgr.uninstall()?;
            eprintln!("sicario: pre-commit hook uninstalled");
        }
        HookAction::Status => {
            let st = mgr.status()?;
            if st.installed {
                eprintln!("sicario: pre-commit hook is installed");
                if let Some(cmd) = &st.command {
                    eprintln!("  command: {cmd}");
                }
            } else {
                eprintln!("sicario: pre-commit hook is not installed");
            }
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Cloud auth commands ──────────────────────────────────────────────────────

fn cmd_cloud_login(args: cli::LoginArgs) -> Result<ExitCode> {
    // Non-interactive path: store the token directly without browser OAuth
    if let Some(token) = args.token {
        use auth::token_store::TokenStore;
        let store = TokenStore::new()?;
        store.store_cloud_token(&token)?;
        eprintln!("Logged in to Sicario Cloud using project token.");
        return Ok(ExitCode::Clean);
    }

    // Interactive path: browser-based device flow
    let client_id =
        std::env::var("SICARIO_CLOUD_CLIENT_ID").unwrap_or_else(|_| "sicario-cli".to_string());
    let auth_url = std::env::var("SICARIO_CLOUD_AUTH_URL")
        .unwrap_or_else(|_| "https://flexible-terrier-680.convex.site".to_string());

    let auth_module = auth::auth_module::AuthModule::new(client_id, auth_url)?;
    auth_module.cloud_login()?;
    Ok(ExitCode::Clean)
}

fn cmd_cloud_logout() -> Result<ExitCode> {
    let client_id =
        std::env::var("SICARIO_CLOUD_CLIENT_ID").unwrap_or_else(|_| "sicario-cli".to_string());
    let auth_url = std::env::var("SICARIO_CLOUD_AUTH_URL")
        .unwrap_or_else(|_| "https://flexible-terrier-680.convex.site".to_string());

    let auth_module = auth::auth_module::AuthModule::new(client_id, auth_url)?;
    auth_module.cloud_logout()?;
    eprintln!("Logged out of Sicario Cloud.");
    Ok(ExitCode::Clean)
}

fn cmd_cloud_whoami() -> Result<ExitCode> {
    let client_id =
        std::env::var("SICARIO_CLOUD_CLIENT_ID").unwrap_or_else(|_| "sicario-cli".to_string());
    let auth_url = std::env::var("SICARIO_CLOUD_AUTH_URL")
        .unwrap_or_else(|_| "https://flexible-terrier-680.convex.site".to_string());

    let auth_module = auth::auth_module::AuthModule::new(client_id, auth_url)?;
    match auth_module.cloud_whoami() {
        Ok(info) => {
            println!("User:         {}", info.username);
            println!("Email:        {}", info.email);
            println!("Organization: {}", info.organization);
            println!("Plan:         {}", info.plan_tier);
            Ok(ExitCode::Clean)
        }
        Err(e) => {
            eprintln!("sicario whoami: {e}");
            Ok(ExitCode::Clean)
        }
    }
}

fn cmd_cloud_publish(org_id: Option<String>) -> Result<ExitCode> {
    use publish::{
        collect_git_metadata, resolve_cloud_url, PublishClient, ScanMetadata, ScanReport,
    };

    // Check authentication
    let client_id =
        std::env::var("SICARIO_CLOUD_CLIENT_ID").unwrap_or_else(|_| "sicario-cli".to_string());
    let auth_url = std::env::var("SICARIO_CLOUD_AUTH_URL")
        .unwrap_or_else(|_| "https://flexible-terrier-680.convex.site".to_string());

    let auth_module = auth::auth_module::AuthModule::new(client_id, auth_url)?;
    let token = match auth_module.get_cloud_token() {
        Ok(t) => t,
        Err(_) => {
            eprintln!("Not logged in to Sicario Cloud. Run `sicario login` first.");
            return Ok(ExitCode::Clean);
        }
    };

    // Run a scan to get findings
    let scan_start = std::time::Instant::now();
    let dir = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let rule_files = discover_bundled_rules();

    let mut eng = engine::sast_engine::SastEngine::new(&dir)?;
    let mut rules_loaded = 0usize;
    for f in &rule_files {
        if eng.load_rules(f).is_ok() {
            rules_loaded += 1;
        }
    }

    // Collect files to get accurate count and language breakdown
    let mut files_to_scan = Vec::new();
    eng.collect_files_recursive(&dir, &mut files_to_scan)?;
    let files_scanned = files_to_scan.len();
    let language_breakdown = build_language_breakdown(&files_to_scan);

    let vulns = eng.scan_directory(&dir)?;
    let scan_duration = scan_start.elapsed();

    let (repository, branch, commit_sha) = collect_git_metadata();

    let findings: Vec<engine::vulnerability::Finding> = vulns
        .iter()
        .map(|v| engine::vulnerability::Finding::from_vulnerability(v, &v.rule_id))
        .collect();

    let metadata = ScanMetadata {
        repository,
        branch,
        commit_sha,
        timestamp: chrono::Utc::now(),
        duration_ms: scan_duration.as_millis() as u64,
        rules_loaded,
        files_scanned,
        language_breakdown,
        tags: Vec::new(),
    };

    let report = ScanReport { findings, metadata };
    let cloud_url = resolve_cloud_url();
    let client = PublishClient::new(cloud_url, token)?.with_org(org_id);

    match client.publish(&report) {
        Ok(resp) => {
            eprintln!(
                "Scan published to Sicario Cloud (scan ID: {}).",
                resp.scan_id
            );
            if let Some(url) = resp.dashboard_url {
                eprintln!("  Dashboard: {url}");
            }
        }
        Err(e) => {
            eprintln!("sicario publish: {e}");
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Interactive TUI ──────────────────────────────────────────────────────────

fn run_interactive_tui(scan_dir: PathBuf) -> Result<()> {
    use tui::app::{create_tui_channel, SicarioTui};
    use tui::worker::{spawn_scan_worker, ScanJob};

    let (tx, rx) = create_tui_channel();
    let mut app = SicarioTui::new(rx)?;

    // Wire the patch sender so the TUI can apply patches from worker threads
    app.patch_tx = Some(tx.clone());

    // Kick off a background scan immediately so the user sees results fast
    let rule_files = discover_bundled_rules();
    let job = ScanJob {
        directory: scan_dir.clone(),
        rule_files,
    };
    spawn_scan_worker(job, tx.clone());

    // Transition straight to Scanning state — skip the static Welcome screen
    app.state = tui::app::AppState::Scanning {
        progress: 0.0,
        files_scanned: 0,
        total_files: 0,
    };

    // Run the blocking TUI event loop
    let result = app.run();

    // Always restore the terminal even on error
    if let Err(ref e) = result {
        eprintln!("sicario: {e}");
    }

    result
}

// ─── Bundled rule discovery ───────────────────────────────────────────────────

/// Find YAML rule files shipped alongside the binary.
///
/// Search order:
///   1. `<binary_dir>/rules/`
///   2. `<cwd>/sicario-cli/rules/`   (source-tree / dev mode)
///   3. `<cwd>/rules/`
///
/// Searches recursively into subdirectories (e.g. `rules/javascript/*.yaml`).
fn discover_bundled_rules() -> Vec<PathBuf> {
    let mut candidates: Vec<PathBuf> = Vec::new();

    if let Ok(exe) = std::env::current_exe() {
        if let Some(parent) = exe.parent() {
            candidates.push(parent.join("rules"));
        }
    }
    if let Ok(cwd) = std::env::current_dir() {
        candidates.push(cwd.join("sicario-cli").join("rules"));
        candidates.push(cwd.join("rules"));
    }

    for dir in candidates {
        if dir.is_dir() {
            let files = collect_yaml_files_recursive(&dir);
            if !files.is_empty() {
                return files;
            }
        }
    }
    Vec::new()
}

/// Recursively collect all `.yaml` / `.yml` files under `dir`.
fn collect_yaml_files_recursive(dir: &std::path::Path) -> Vec<PathBuf> {
    let mut result = Vec::new();
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.filter_map(|e| e.ok()) {
            let path = entry.path();
            if path.is_dir() {
                result.extend(collect_yaml_files_recursive(&path));
            } else if path
                .extension()
                .and_then(|e| e.to_str())
                .map(|e| e == "yaml" || e == "yml")
                .unwrap_or(false)
            {
                result.push(path);
            }
        }
    }
    result
}

// ─── Benchmark command ─────────────────────────────────────────────────────────

fn cmd_benchmark(args: cli::benchmark::BenchmarkArgs) -> Result<ExitCode> {
    use benchmark::BenchmarkRunner;

    let project_root = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let rule_files = discover_bundled_rules();
    let runner = BenchmarkRunner::new(&project_root, rule_files);

    let result = runner.run(&project_root)?;

    // Compare against baseline if requested
    if let Some(ref baseline_name) = args.compare_baseline {
        let baseline = if baseline_name == "latest" {
            runner.load_latest_baseline()?
        } else {
            runner.load_baseline(baseline_name)?
        };

        if let Some(baseline) = baseline {
            let comparison = BenchmarkRunner::compare(&baseline, &result);
            if args.format == "json" {
                println!("{}", serde_json::to_string_pretty(&comparison)?);
            } else {
                print!("{}", comparison.display_text());
            }
            return Ok(ExitCode::Clean);
        } else {
            eprintln!("warning: no baseline found for comparison");
        }
    }

    // Output result
    if args.format == "json" {
        println!("{}", serde_json::to_string_pretty(&result)?);
    } else {
        print!("{}", result.display_text());
    }

    Ok(ExitCode::Clean)
}

// ─── Rules command ────────────────────────────────────────────────────────────

fn cmd_rules(args: cli::rules::RulesCommand) -> Result<ExitCode> {
    use cli::rules::RulesAction;
    use engine::sast_engine::SastEngine;
    use rule_harness::{RuleQualityValidation, RuleTestHarness};

    let project_root = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let rule_files = discover_bundled_rules();

    // Load all rules
    let mut engine = SastEngine::new(&project_root)?;
    for f in &rule_files {
        if let Err(e) = engine.load_rules(f) {
            eprintln!("warning: could not load {:?}: {e}", f);
        }
    }
    let rules = engine.get_rules().to_vec();
    let harness = RuleTestHarness::new(&project_root);

    match args.action {
        RulesAction::Test(test_args) => {
            eprintln!("Running rule test cases for {} rules...", rules.len());
            let report = harness.validate_all(&rules)?;

            if test_args.report {
                if report.aggregate_fp_rate >= 0.15 {
                    eprintln!(
                        "⚠ Aggregate FP rate {:.1}% exceeds 15% threshold",
                        report.aggregate_fp_rate * 100.0
                    );
                }
                println!("{}", serde_json::to_string_pretty(&report)?);
            } else {
                print!("{}", report.display_text());
            }

            if report.invalid_rules > 0 {
                return Ok(ExitCode::FindingsDetected);
            }
        }
        RulesAction::Validate(validate_args) => {
            eprintln!("Validating {} rules...", rules.len());
            let report = harness.validate_all_syntax(&rules);

            if validate_args.report {
                println!("{}", serde_json::to_string_pretty(&report)?);
            } else {
                print!("{}", report.display_text());
            }

            if report.invalid_rules > 0 {
                return Ok(ExitCode::FindingsDetected);
            }
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Fix command ──────────────────────────────────────────────────────────────

/// Normalise a path by resolving `.` and `..` components without calling
/// `std::fs::canonicalize()`.  Canonicalize is avoided because on Windows it
/// produces UNC-prefixed paths (`\\?\C:\...`) that don't compare equal to the
/// plain absolute paths returned by `std::fs::read_dir`.
fn normalize_path(path: &std::path::Path) -> PathBuf {
    use std::path::Component;
    let mut out = PathBuf::new();
    for component in path.components() {
        match component {
            Component::CurDir => {} // skip `.`
            Component::ParentDir => {
                out.pop(); // resolve `..`
            }
            c => out.push(c),
        }
    }
    out
}

fn cmd_fix(args: cli::fix::FixArgs) -> Result<ExitCode> {
    use remediation::iteration_guard::IterationGuard;
    use remediation::remediation_engine::RemediationEngine;
    use verification::scanner::VerificationScanning;

    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));

    // Handle revert
    if let Some(ref patch_id) = args.revert {
        let engine = RemediationEngine::new(&cwd)?;
        engine.revert_by_patch_id(patch_id)?;
        eprintln!("sicario: reverted patch {patch_id}");
        return Ok(ExitCode::Clean);
    }

    // Resolve --max-iterations (also reads SICARIO_MAX_ITERATIONS via clap env)
    let max_iterations = match args.resolve_max_iterations() {
        Ok(n) => n,
        Err(msg) => {
            eprintln!("sicario: {msg}");
            return Ok(ExitCode::InternalError);
        }
    };

    let file_path = PathBuf::from(&args.file);
    if !file_path.exists() {
        eprintln!("sicario fix: file not found: {}", args.file);
        return Ok(ExitCode::InternalError);
    }
    // Resolve to an absolute path without going through canonicalize(), which
    // on Windows produces UNC-prefixed paths (\\?\C:\...) that don't compare
    // equal to the plain absolute paths returned by std::fs::read_dir.
    let file_path = if file_path.is_absolute() {
        file_path
    } else {
        cwd.join(&file_path)
    };
    // Normalise away any `.` or `..` components that were introduced by a
    // `./`-prefixed argument (e.g. `./app/data/user-dao.js`).  We cannot use
    // `canonicalize()` here because on Windows it produces UNC-prefixed paths
    // (`\\?\C:\...`) that don't compare equal to the plain absolute paths
    // returned by `std::fs::read_dir`.
    let file_path = normalize_path(&file_path);

    let is_dir = file_path.is_dir();

    // Scan the file/directory to find vulnerabilities.
    // Use embedded rules (same as cmd_scan) so the full 500+ rule set is active.
    let scan_root = if is_dir {
        file_path.clone()
    } else {
        file_path.parent().unwrap_or(&cwd).to_path_buf()
    };
    let mut eng = engine::sast_engine::SastEngine::new(&cwd)?;
    let embedded_count = load_embedded_rules_into(&mut eng);
    if embedded_count == 0 {
        // Fallback: try disk rules (dev environment)
        for f in discover_bundled_rules() {
            let _ = eng.load_rules(&f);
        }
        if eng.get_rules().is_empty() {
            eng.load_default_rules();
        }
    }
    let vulns = eng.scan_directory(&scan_root)?;

    // Normalise both sides to lowercase strings for a case-insensitive,
    // separator-insensitive comparison (handles Windows drive-letter casing
    // and mixed slash styles).
    let target = file_path
        .to_string_lossy()
        .replace('\\', "/")
        .to_lowercase();

    // Filter to the target file (or all files under the target directory)
    // and optionally the specified rule.
    let file_vulns: Vec<_> = vulns
        .iter()
        .filter(|v| {
            let vpath = v
                .file_path
                .to_string_lossy()
                .replace('\\', "/")
                .to_lowercase();
            if is_dir {
                // Directory: match any file whose path starts with the target dir
                vpath.starts_with(&target)
            } else {
                vpath == target
            }
        })
        .filter(|v| args.rule.as_ref().is_none_or(|r| v.rule_id == *r))
        .collect();

    if file_vulns.is_empty() {
        eprintln!("sicario fix: no findings in {}", args.file);
        return Ok(ExitCode::Clean);
    }

    let engine = RemediationEngine::new_with_allow_ai(&cwd, args.allow_ai)?;

    if args.yes {
        // Batch mode: process all vulnerabilities without per-fix prompts
        let rule_files = discover_bundled_rules();
        let batch = engine.generate_and_apply_batch(
            &file_vulns,
            true, // auto_confirm
            args.no_verify,
            &rule_files,
        )?;
        eprintln!(
            "sicario: batch complete — {} applied, {} reverted, {} skipped",
            batch.applied, batch.reverted, batch.skipped
        );
    } else {
        // Interactive mode: confirm each fix individually, with iteration cap
        for vuln in &file_vulns {
            let mut guard = IterationGuard::new(max_iterations, &cwd);
            let fix_start = std::time::Instant::now();
            let patch = loop {
                match engine.generate_patch(vuln) {
                    Ok(p) => break p,
                    Err(e) => {
                        let reason = e.to_string();
                        eprintln!(
                            "sicario: fix attempt {}/{} failed for {} — {reason}",
                            guard.attempts() + 1,
                            max_iterations,
                            vuln.rule_id
                        );
                        if guard.record_failure(reason).is_err() {
                            // Iteration cap reached — log diagnostic and block CI
                            let file_str = vuln.file_path.to_string_lossy();
                            if let Err(log_err) = guard.flush_trace_log(&vuln.rule_id, &file_str) {
                                eprintln!(
                                    "sicario: warning — could not write trace log: {log_err}"
                                );
                            }
                            eprintln!(
                                "sicario: error — could not produce a valid fix for {} in {} \
                                 after {max_iterations} attempt(s). \
                                 Diagnostic written to .sicario/trace.log",
                                vuln.rule_id,
                                vuln.file_path.display()
                            );
                            return Ok(ExitCode::FindingsDetected);
                        }
                    }
                }
            };

            let confirmed = engine.display_diff_and_confirm(&patch)?;
            if confirmed {
                engine.apply_patch(&patch)?;
                let execution_ms = fix_start.elapsed().as_millis();
                eprintln!("sicario: patch applied to {}", args.file);

                // Emit zero-exfiltration receipt (unless suppressed with --no-receipt)
                if !args.no_receipt {
                    let receipt = remediation::PatchReceipt::deterministic(
                        &vuln.rule_id,
                        &args.file,
                        vuln.line as u32,
                        execution_ms,
                        &vuln.rule_id,
                    );
                    receipt.print();
                }

                // Post-fix verification
                if !args.no_verify {
                    let mut verifier = verification::VerificationScanner::new(&cwd);
                    let original = verification::OriginalFinding {
                        rule_id: vuln.rule_id.clone(),
                        fingerprint: engine::vulnerability::Finding::compute_fingerprint(
                            &vuln.rule_id,
                            &vuln.file_path,
                            &vuln.snippet,
                        ),
                        file_path: vuln.file_path.clone(),
                    };
                    let rule_files = discover_bundled_rules();
                    match verifier.verify_fix(&file_path, &original, &rule_files)? {
                        verification::VerificationResult::Resolved => {
                            eprintln!("sicario: fix verified — vulnerability resolved");
                        }
                        verification::VerificationResult::StillPresent => {
                            eprintln!("sicario: warning — vulnerability still present after fix");
                        }
                        verification::VerificationResult::NewFindingsIntroduced(new) => {
                            eprintln!(
                                "sicario: warning — fix introduced {} new finding(s)",
                                new.len()
                            );
                        }
                    }
                }
            } else {
                eprintln!("sicario: patch skipped");
            }
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Baseline command ─────────────────────────────────────────────────────────

fn cmd_baseline(args: cli::baseline::BaselineCommand) -> Result<ExitCode> {
    use baseline::manager::{BaselineManagement, BaselineManager};
    use cli::baseline::BaselineAction;

    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let mgr = BaselineManager::new(&cwd);

    match args.action {
        BaselineAction::Save(save_args) => {
            // Run a scan to get current findings
            let rule_files = discover_bundled_rules();
            let mut eng = engine::sast_engine::SastEngine::new(&cwd)?;
            for f in &rule_files {
                let _ = eng.load_rules(f);
            }
            let vulns = eng.scan_directory(&cwd)?;
            let findings: Vec<engine::vulnerability::Finding> = vulns
                .iter()
                .map(|v| engine::vulnerability::Finding::from_vulnerability(v, &v.rule_id))
                .collect();

            let path = mgr.save(&findings, save_args.tag.as_deref())?;
            eprintln!("sicario: baseline saved to {}", path.display());
        }
        BaselineAction::Compare(cmp_args) => {
            // Run a scan to get current findings
            let rule_files = discover_bundled_rules();
            let mut eng = engine::sast_engine::SastEngine::new(&cwd)?;
            for f in &rule_files {
                let _ = eng.load_rules(f);
            }
            let vulns = eng.scan_directory(&cwd)?;
            let findings: Vec<engine::vulnerability::Finding> = vulns
                .iter()
                .map(|v| engine::vulnerability::Finding::from_vulnerability(v, &v.rule_id))
                .collect();

            let delta = mgr.compare(&cmp_args.reference, &findings)?;
            if cmp_args.format == "json" {
                println!("{}", serde_json::to_string_pretty(&delta)?);
            } else {
                eprintln!(
                    "New: {}  Resolved: {}  Unchanged: {}",
                    delta.new_findings.len(),
                    delta.resolved_findings.len(),
                    delta.unchanged_findings.len()
                );
            }
        }
        BaselineAction::Trend(trend_args) => {
            let summaries = mgr.trend()?;
            if trend_args.format == "json" {
                println!("{}", serde_json::to_string_pretty(&summaries)?);
            } else {
                for s in &summaries {
                    eprintln!(
                        "{} {}: {} findings (C:{} H:{} M:{} L:{} I:{})",
                        s.timestamp.format("%Y-%m-%d %H:%M"),
                        s.tag.as_deref().unwrap_or("-"),
                        s.total_findings,
                        s.critical_count,
                        s.high_count,
                        s.medium_count,
                        s.low_count,
                        s.info_count,
                    );
                }
            }
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Config command ───────────────────────────────────────────────────────────

fn cmd_config(args: cli::config::ConfigCommand) -> Result<ExitCode> {
    use cli::config::ConfigAction;

    match args.action {
        ConfigAction::SetKey => {
            eprintln!("Enter your LLM API key: ");
            let mut key = String::new();
            std::io::stdin().read_line(&mut key)?;
            let key = key.trim();
            if key.is_empty() {
                eprintln!("sicario config: no key provided");
                return Ok(ExitCode::Clean);
            }
            key_manager::store_key_in_keyring(key)?;
            eprintln!("sicario: API key stored in OS credential store");
        }
        ConfigAction::Set(set_args) => {
            config::set_global_config_value(&set_args.key, &set_args.value)?;
            let path = config::global_config_path()
                .map(|p| p.display().to_string())
                .unwrap_or_else(|| "~/.sicario/config.toml".to_string());
            eprintln!("sicario: {} saved to {}", set_args.key, path);
            eprintln!("  Note: LLM keys are stored locally and never sent to Sicario Cloud.");
            eprintln!("  SICARIO_API_KEY is separate — it authenticates telemetry uploads only.");
        }
        ConfigAction::SetProvider(provider_args) => {
            use key_manager::{find_provider, PROVIDERS};

            // Determine endpoint and model from either the named preset or explicit flags
            let (endpoint, model, provider_name) = if let Some(ref name) = provider_args.name {
                match find_provider(name) {
                    Some(preset) => {
                        let ep = provider_args
                            .endpoint
                            .clone()
                            .unwrap_or_else(|| preset.endpoint.to_string());
                        let mdl = provider_args
                            .model
                            .clone()
                            .unwrap_or_else(|| preset.default_model.to_string());
                        (ep, mdl, preset.name.to_string())
                    }
                    None => {
                        let valid: Vec<&str> = PROVIDERS.iter().map(|p| p.name).collect();
                        eprintln!(
                            "Unknown provider '{}'. Valid providers: {}",
                            name,
                            valid.join(", ")
                        );
                        return Ok(ExitCode::InternalError);
                    }
                }
            } else if let Some(ref ep) = provider_args.endpoint {
                let mdl = provider_args
                    .model
                    .clone()
                    .unwrap_or_else(|| "gpt-4o-mini".to_string());
                (ep.clone(), mdl, "custom".to_string())
            } else {
                eprintln!("sicario config set-provider: provide a provider name or --endpoint");
                return Ok(ExitCode::InternalError);
            };

            // Write llm_endpoint and llm_model to ~/.sicario/config.toml (global config)
            config::set_global_config_value("llm_endpoint", &endpoint)?;
            config::set_global_config_value("llm_model", &model)?;

            let config_path = config::global_config_path()
                .map(|p| p.display().to_string())
                .unwrap_or_else(|| "~/.sicario/config.toml".to_string());
            eprintln!(
                "Provider set to {}: endpoint={}, model={}",
                provider_name, endpoint, model
            );
            eprintln!("  Written to {}", config_path);
        }
        ConfigAction::Show => {
            use key_manager::PROVIDERS;

            // ── Provider table (all 19 providers) ────────────────────────────
            println!("Supported LLM Providers ({} total):", PROVIDERS.len());
            println!();

            // Compute column widths dynamically for clean alignment
            let name_w = PROVIDERS
                .iter()
                .map(|p| p.name.len())
                .max()
                .unwrap_or(10)
                .max(4);
            let ep_w = 55usize; // truncate long endpoints to keep table readable
            let model_w = PROVIDERS
                .iter()
                .map(|p| {
                    if p.default_model.is_empty() {
                        26
                    } else {
                        p.default_model.len()
                    }
                })
                .max()
                .unwrap_or(13)
                .max(13);
            let envvar_w = PROVIDERS
                .iter()
                .map(|p| {
                    if p.env_var.is_empty() {
                        6
                    } else {
                        p.env_var.len()
                    }
                })
                .max()
                .unwrap_or(7)
                .max(7);

            // Header
            println!(
                "{:<name_w$}  {:<ep_w$}  {:<model_w$}  {:<envvar_w$}",
                "NAME",
                "ENDPOINT",
                "DEFAULT MODEL",
                "ENV VAR",
                name_w = name_w,
                ep_w = ep_w,
                model_w = model_w,
                envvar_w = envvar_w,
            );
            println!(
                "{:-<name_w$}  {:-<ep_w$}  {:-<model_w$}  {:-<envvar_w$}",
                "",
                "",
                "",
                "",
                name_w = name_w,
                ep_w = ep_w,
                model_w = model_w,
                envvar_w = envvar_w,
            );

            for p in PROVIDERS {
                let endpoint_display = if p.endpoint.len() > ep_w {
                    format!("{}…", &p.endpoint[..ep_w - 1])
                } else {
                    p.endpoint.to_string()
                };
                let model_display = if p.default_model.is_empty() {
                    "(local — auto-detected)".to_string()
                } else {
                    p.default_model.to_string()
                };
                let envvar_display = if p.env_var.is_empty() {
                    "(none)".to_string()
                } else {
                    p.env_var.to_string()
                };
                println!(
                    "{:<name_w$}  {:<ep_w$}  {:<model_w$}  {:<envvar_w$}",
                    p.name,
                    endpoint_display,
                    model_display,
                    envvar_display,
                    name_w = name_w,
                    ep_w = ep_w,
                    model_w = model_w,
                    envvar_w = envvar_w,
                );
            }

            // ── Active key source (no network request, no key value) ──────────
            println!();
            let key_source = key_manager::resolve_key_source_no_network();
            let active_label = match &key_source {
                key_manager::KeySource::None => "not configured".to_string(),
                key_manager::KeySource::Keyring => "OS keyring".to_string(),
                key_manager::KeySource::ConfigFile => ".sicario/config.yaml".to_string(),
                other => format!("{} env var", other.label()),
            };
            println!("Active key source: {}", active_label);
            if key_source == key_manager::KeySource::None {
                println!("  Run `sicario config set-key <key>` or set OPENAI_API_KEY / ANTHROPIC_API_KEY.");
            }

            println!();
            println!("Use `sicario config set-provider <name>` to switch providers.");
        }
        ConfigAction::DeleteKey => {
            key_manager::delete_key_from_keyring()?;
            eprintln!("sicario: API key removed from OS credential store");
        }
        ConfigAction::Test => {
            let key = key_manager::resolve_api_key();
            if key.is_none() {
                eprintln!(
                    "sicario config test: no API key configured. Run `sicario config set-key`."
                );
                return Ok(ExitCode::Clean);
            }
            let endpoint = key_manager::resolve_endpoint();
            let model = key_manager::resolve_model();
            eprintln!("Testing connectivity to {endpoint} with model {model}...");
            // Simple connectivity check via reqwest
            let client = reqwest::blocking::Client::builder()
                .timeout(std::time::Duration::from_secs(10))
                .build()?;
            let key = key.unwrap();
            let resp = client
                .post(&endpoint)
                .header("Authorization", format!("Bearer {}", key.key))
                .header("Content-Type", "application/json")
                .body(format!(
                    r#"{{"model":"{}","messages":[{{"role":"user","content":"ping"}}],"max_tokens":1}}"#,
                    model
                ))
                .send();
            match resp {
                Ok(r) if r.status().is_success() => {
                    eprintln!(
                        "sicario: connection successful (key source: {})",
                        key.source.label()
                    );
                }
                Ok(r) => {
                    eprintln!("sicario: server responded with status {}", r.status());
                }
                Err(e) => {
                    eprintln!("sicario: connection failed: {e}");
                }
            }
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Cache command ────────────────────────────────────────────────────────────

fn cmd_cache(args: cli::cache::CacheCommand) -> Result<ExitCode> {
    use cache::scan_cache::ScanCaching;
    use cache::ScanCache;
    use cli::cache::CacheAction;

    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let mut cache = ScanCache::new(&cwd)?;

    match args.action {
        CacheAction::Clear => {
            cache.clear()?;
            eprintln!("sicario: scan cache cleared");
        }
        CacheAction::Stats => {
            let stats = cache.stats()?;
            println!("Cached files: {}", stats.cached_files);
            println!("Size:         {} bytes", stats.size_bytes);
            if let Some(oldest) = stats.oldest_entry {
                println!("Oldest entry: {}", oldest.format("%Y-%m-%d %H:%M:%S"));
            }
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Report handler (preserved from original) ────────────────────────────────

fn cmd_report_handler(dir_str: &str, output: Option<&str>) -> Result<()> {
    use engine::sast_engine::SastEngine;
    use reporting::{generate_compliance_report, write_compliance_reports};

    let dir = PathBuf::from(dir_str);
    let output_dir = output
        .map(PathBuf::from)
        .unwrap_or_else(|| dir.join(".sicario").join("reports"));

    let mut eng = SastEngine::new(&dir)?;
    for f in discover_bundled_rules() {
        if let Err(e) = eng.load_rules(&f) {
            eprintln!("warning: could not load {:?}: {e}", f);
        }
    }

    let vulns = eng.scan_directory(&dir)?;
    let report = generate_compliance_report(&vulns);
    let (json_path, md_path) = write_compliance_reports(&report, &output_dir)?;

    println!("OWASP report: {}", json_path.display());
    println!("Markdown:     {}", md_path.display());
    println!(
        "Total: {}  |  Categories affected: {}/10",
        report.total_vulnerabilities, report.categories_affected
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use engine::sast_engine::SastEngine;
    use std::fs;
    use std::io::Write;
    use tempfile::TempDir;

    /// Helper: create a minimal valid YAML rule file in `dir`.
    fn write_valid_yaml_rule(dir: &std::path::Path, filename: &str) {
        let content = r#"
- id: test-rule-001
  name: "Test Rule"
  description: "Test rule for warning tests"
  severity: Low
  languages:
    - JavaScript
  pattern:
    query: "(call_expression function: (identifier) @fn (#eq? @fn \"eval\")) @call"
    captures:
      - "call"
  cwe_id: "CWE-95"
"#;
        let path = dir.join(filename);
        let mut f = fs::File::create(&path).unwrap();
        f.write_all(content.as_bytes()).unwrap();
    }

    /// Helper: create a non-YAML file in `dir`.
    fn write_non_yaml_file(dir: &std::path::Path, filename: &str) {
        let path = dir.join(filename);
        fs::write(&path, "this is not yaml").unwrap();
    }

    // ── Test 1: non-existent path ─────────────────────────────────────────────

    /// When `--rules-dir` points to a path that does not exist, `load_rules_from_dir`
    /// must return 0 rules loaded and a warning message containing the path.
    ///
    /// Validates: Requirement 17.4 (IF the path does not exist … print a warning
    /// and continue with built-in rules only)
    #[test]
    fn test_rules_dir_nonexistent_returns_warning() {
        let temp = TempDir::new().unwrap();
        let nonexistent = temp.path().join("does_not_exist");
        let path_str = nonexistent.to_string_lossy().to_string();

        let mut eng = SastEngine::new(temp.path()).unwrap();
        let (loaded, warning) = load_rules_from_dir(&path_str, &mut eng, /*quiet=*/ true);

        assert_eq!(
            loaded, 0,
            "No rules should be loaded from a non-existent path"
        );
        let warning = warning.expect("A warning message must be returned for a non-existent path");
        assert!(
            warning.contains("[sicario] warning"),
            "Warning must carry the [sicario] prefix; got: {warning}"
        );
        assert!(
            warning.contains(&path_str),
            "Warning must include the offending path; got: {warning}"
        );
        assert!(
            warning.to_lowercase().contains("does not exist"),
            "Warning must mention that the path does not exist; got: {warning}"
        );
        assert!(
            warning.to_lowercase().contains("built-in rules only"),
            "Warning must mention falling back to built-in rules; got: {warning}"
        );
    }

    /// A non-existent `--rules-dir` must NOT cause the engine to lose any rules
    /// that were already loaded — the scan continues with built-in rules only.
    ///
    /// Validates: Requirement 17.4 (continue with built-in rules only)
    #[test]
    fn test_rules_dir_nonexistent_does_not_clear_existing_rules() {
        let temp = TempDir::new().unwrap();
        let rules_dir = temp.path().join("valid_rules");
        fs::create_dir_all(&rules_dir).unwrap();
        write_valid_yaml_rule(&rules_dir, "rule.yaml");

        let mut eng = SastEngine::new(temp.path()).unwrap();
        // Pre-load a rule so the engine is non-empty.
        let rule_path = rules_dir.join("rule.yaml");
        eng.load_rules(&rule_path).unwrap();
        let rules_before = eng.get_rules().len();
        assert!(rules_before > 0, "Engine must have rules before the test");

        // Now attempt to load from a non-existent path.
        let nonexistent = temp.path().join("ghost_dir");
        let path_str = nonexistent.to_string_lossy().to_string();
        let (loaded, _) = load_rules_from_dir(&path_str, &mut eng, /*quiet=*/ true);

        assert_eq!(loaded, 0);
        assert_eq!(
            eng.get_rules().len(),
            rules_before,
            "Existing rules must be preserved when rules-dir does not exist"
        );
    }

    // ── Test 2: path exists but contains no valid YAML files ──────────────────

    /// When `--rules-dir` points to an empty directory, `load_rules_from_dir`
    /// must return 0 rules loaded and a warning message.
    ///
    /// Validates: Requirement 17.4 (IF … contains no valid YAML rule files …
    /// print a warning and continue with built-in rules only)
    #[test]
    fn test_rules_dir_empty_directory_returns_warning() {
        let temp = TempDir::new().unwrap();
        let empty_dir = temp.path().join("empty_rules");
        fs::create_dir_all(&empty_dir).unwrap();
        let path_str = empty_dir.to_string_lossy().to_string();

        let mut eng = SastEngine::new(temp.path()).unwrap();
        let (loaded, warning) = load_rules_from_dir(&path_str, &mut eng, /*quiet=*/ true);

        assert_eq!(
            loaded, 0,
            "No rules should be loaded from an empty directory"
        );
        let warning = warning.expect("A warning message must be returned for an empty rules-dir");
        assert!(
            warning.contains("[sicario] warning"),
            "Warning must carry the [sicario] prefix; got: {warning}"
        );
        assert!(
            warning.contains(&path_str),
            "Warning must include the offending path; got: {warning}"
        );
        assert!(
            warning.to_lowercase().contains("no valid yaml"),
            "Warning must mention no valid YAML files; got: {warning}"
        );
        assert!(
            warning.to_lowercase().contains("built-in rules only"),
            "Warning must mention falling back to built-in rules; got: {warning}"
        );
    }

    /// When `--rules-dir` contains only non-YAML files, `load_rules_from_dir`
    /// must return 0 rules loaded and a warning message.
    ///
    /// Validates: Requirement 17.4 (no valid YAML rule files → warning + continue)
    #[test]
    fn test_rules_dir_no_yaml_files_returns_warning() {
        let temp = TempDir::new().unwrap();
        let rules_dir = temp.path().join("non_yaml_rules");
        fs::create_dir_all(&rules_dir).unwrap();
        write_non_yaml_file(&rules_dir, "readme.txt");
        write_non_yaml_file(&rules_dir, "config.json");
        let path_str = rules_dir.to_string_lossy().to_string();

        let mut eng = SastEngine::new(temp.path()).unwrap();
        let (loaded, warning) = load_rules_from_dir(&path_str, &mut eng, /*quiet=*/ true);

        assert_eq!(loaded, 0, "Non-YAML files must not count as loaded rules");
        let warning = warning.expect("A warning must be returned when no YAML files are present");
        assert!(
            warning.contains("[sicario] warning"),
            "Warning must carry the [sicario] prefix; got: {warning}"
        );
        assert!(
            warning.to_lowercase().contains("no valid yaml"),
            "Warning must mention no valid YAML files; got: {warning}"
        );
    }

    // ── Test 3: happy path — valid YAML files load without warning ────────────

    /// When `--rules-dir` contains valid YAML rule files, `load_rules_from_dir`
    /// must return the count of loaded rules and no warning.
    ///
    /// Validates: Requirement 17.3 (load rules from the specified directory)
    #[test]
    fn test_rules_dir_valid_yaml_loads_without_warning() {
        let temp = TempDir::new().unwrap();
        let rules_dir = temp.path().join("good_rules");
        fs::create_dir_all(&rules_dir).unwrap();
        write_valid_yaml_rule(&rules_dir, "rule.yaml");
        let path_str = rules_dir.to_string_lossy().to_string();

        let mut eng = SastEngine::new(temp.path()).unwrap();
        let (loaded, warning) = load_rules_from_dir(&path_str, &mut eng, /*quiet=*/ true);

        assert!(
            loaded > 0,
            "At least one rule must be loaded from a valid rules-dir"
        );
        assert!(
            warning.is_none(),
            "No warning should be emitted when valid YAML rules are present; got: {warning:?}"
        );
    }

    // ── Test 4: quiet flag suppresses stderr output ───────────────────────────

    /// The `quiet` flag must suppress the warning from being printed to stderr,
    /// but the warning string must still be returned so callers can inspect it.
    ///
    /// Validates: Requirement 17.4 (warning behaviour is consistent with quiet mode)
    #[test]
    fn test_rules_dir_nonexistent_quiet_still_returns_warning_string() {
        let temp = TempDir::new().unwrap();
        let nonexistent = temp.path().join("ghost");
        let path_str = nonexistent.to_string_lossy().to_string();

        let mut eng = SastEngine::new(temp.path()).unwrap();
        // quiet=true: no eprintln, but the warning string is still returned.
        let (loaded, warning) = load_rules_from_dir(&path_str, &mut eng, /*quiet=*/ true);

        assert_eq!(loaded, 0);
        assert!(
            warning.is_some(),
            "Warning string must be returned even in quiet mode"
        );
    }
}
